### ISSUE TITLE
async_resolve background thread

### ISSUE THREAD

**Issue by daniel-mdb** [chriskohlhoff/asio#1033]
MongoDB in its version 5.3 relies on both synchronous and asynchronous ASIO APIs due latency constrains. The asynchronous client that lies within always resolve before connecting by calling into [`TransportLayerASIO::_async_resolve`](https://github.com/mongodb/mongo/blob/v5.3/src/mongo/transport/transport_layer_asio.cpp#L491-L504). Internal reports showed ASIO `posix_thread` leaks sometimes, which could be synthetically reproduced by the fragment attached below. While the leak is no library's fault, I find curious `async_resolve` creates a background thread to resolve, rather than calling something like `getaddrinfo_a` and would like to understand the motivations behind this decision. Internally, I am making a recommendation to, in order to simplify the networking layer, strip the name resolution from the "connecting" mechanics and possibly rely into ASIO's blocking resolver as I believe it would fit Mongo's use case better. Would you mind sharing any considerations on this approach as well?

```
$  git diff ; cat async-resolver.cc ;  g++ -O0 -g -fsanitize=address -I asio/include/ asio/src/asio.cpp async-resolver.cc -lpthread && ./a.out
--
diff --git a/src/third_party/asio-master/asio/include/asio/detail/posix_thread.hpp b/src/third_party/asio-master/asio/include/asio/detail/posix_thread.hpp
index 1817af28d4..8a9a066e31 100644
--- a/src/third_party/asio-master/asio/include/asio/detail/posix_thread.hpp
+++ b/src/third_party/asio-master/asio/include/asio/detail/posix_thread.hpp
@@ -67,7 +67,7 @@ private:
struct auto_func_base_ptr
{
func_base* ptr;
-    ~auto_func_base_ptr() { delete ptr; }
+    ~auto_func_base_ptr() { /* delete ptr; */ }
};
 
template <typename Function>
#include <chrono>
#include "asio/include/asio.hpp"
 
int main() {
asio::ip::resolver_base::flags flags;
using Resolver = asio::ip::tcp::resolver;
using Results = Resolver::results_type;
asio::io_context _ioContext;
asio::io_context::work work(_ioContext);
Resolver _resolver(_ioContext);
_resolver.async_resolve("www.mongodb.com", "443", [](std::error_code, Results){printf("completed\n");});
_ioContext.run_one(); //_for(std::chrono::microseconds(10));
return 0;
}
completed
 
=================================================================
==2349==ERROR: LeakSanitizer: detected memory leaks
 
Direct leak of 16 byte(s) in 1 object(s) allocated from:
#0 0x7f743c856448 in operator new(unsigned long) (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xe0448)
#1 0x5556b2e8d7ba in asio::detail::posix_thread::posix_thread<asio::detail::resolver_service_base::work_io_context_runner>(asio::detail::resolver_service_base::work_io_context_runner, unsigned int) (/home/ubuntu/mongo/src/third_party/asio-master/a.out+0x4b7ba)
#2 0x5556b2e5f7eb in asio::detail::resolver_service_base::start_work_thread() asio/include/asio/detail/impl/resolver_service_base.ipp:145
#3 0x5556b2e5f5c6 in asio::detail::resolver_service_base::start_resolve_op(asio::detail::resolve_op*) asio/include/asio/detail/impl/resolver_service_base.ipp:128
#4 0x5556b2e96606 in async_resolve<main()::<lambda(std::error_code, Results)> > asio/include/asio/detail/resolver_service.hpp:101
#5 0x5556b2e9613f in async_resolve<main()::<lambda(std::error_code, Results)> > asio/include/asio/ip/basic_resolver.hpp:776
#6 0x5556b2e95e2b in async_resolve<main()::<lambda(std::error_code, Results)> > asio/include/asio/ip/basic_resolver.hpp:703
#7 0x5556b2e95bfc in main /home/ubuntu/mongo/src/third_party/asio-master/async-resolver.cc:11
#8 0x7f743bbe6bf6 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x21bf6)
 
SUMMARY: AddressSanitizer: 16 byte(s) leaked in 1 allocation(s).
```

**Comment by vinipsmaker** [comment]
Close the issue. It's a duplicate of <https://github.com/chriskohlhoff/asio/issues/449>.
